In [1]:
!conda info

     active environment : env_gofood
    active env location : C:\Users\ASUS\anaconda3\envs\env_gofood
            shell level : 1
       user config file : C:\Users\ASUS\.condarc
 populated config files : C:\Users\ASUS\.condarc
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\ASUS\anaconda3  (writable)
      conda av data dir : C:\Users\ASUS\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\ASUS\anaconda3\pkgs
                          C:\Users\ASUS\.conda\pkgs
                          C:\Users\ASUS\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\ASUS\anaconda3\envs
                          C:\Users\ASUS\.conda\envs
                          C:\Users\ASUS\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

In [2]:
!python --version

Python 3.10.8

In [3]:
%conda install pandas

Collecting package metadata (current_repodata.json): ...working... done
Note: you may need to restart the kernel to use updated packages.

Solving environment: ...working... done

## Package Plan ##

  environment location: c:\Users\ASUS\anaconda3\envs\env_gofood

  added / updated specs:
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pandas-1.5.2               |  py310h4ed8f06_0        10.5 MB
    ------------------------------------------------------------
                                           Total:        10.5 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl None
  bottleneck         pkgs/main/win-64::bottleneck-1.3.5-py310h9128911_0 None
  intel-openmp       pkgs/main/win-64::intel-openmp-2021.4.0-haa95532_3556 None
  mkl                pkgs/main/win-64::mkl-2021.4.0-haa95532_640 None
  mkl-service        pkgs/main/win-64::mkl-service-2.4.0-py310h2bbff1b_0 None
  mkl_fft            pkgs/main/win-64::mkl_fft-1.3.1-py310ha0764ea_0 None
  mkl_random         pkgs/main/win-64::mkl_random-1.2.2-py310h4ed8f06_0 None
  numexpr            pkgs/main/win-64::numexpr-2.8.4-py310hd213c9f_0 None
  numpy              pkgs/main/win-64::numpy-1.23.4-py310h60c9a35_0 None
  numpy-base         pkgs/main/win-64::numpy-base-1.23.4-py310h04254f7_0 None
  pandas             pkgs/main/win-64::pandas-1.5.2-py310h4ed8f06_0 None



Downloading and Extracting Packages

pandas-1.5.2         | 10.5 MB   |            |   0%
pandas-1.5.2         | 10.5 MB   |            |   0%
pandas-1.5.2         | 10.5 MB   | 1          |   2%
pandas-1.5.2         | 10.5 MB   | 3          |   3%
pandas-1.5.2         | 10.5 MB   | 5          |   5%
pandas-1.5.2         | 10.5 MB   | 8          |   8%
pandas-1.5.2         | 10.5 MB   | #          |  10%
pandas-1.5.2         | 10.5 MB   | #3         |  13%
pandas-1.5.2         | 10.5 MB   | #6         |  17%
pandas-1.5.2         | 10.5 MB   | #9         |  19%
pandas-1.5.2         | 10.5 MB   | ##2        |  23%
pandas-1.5.2         | 10.5 MB   | ##5        |  25%
pandas-1.5.2         | 10.5 MB   | ##8        |  28%
pandas-1.5.2         | 10.5 MB   | ###1       |  31%
pandas-1.5.2         | 10.5 MB   | ###4       |  34%
pandas-1.5.2         | 10.5 MB   | ###7       |  37%
pandas-1.5.2         | 10.5 MB   | ####       |  40%
pandas-1.5.2         | 10.5 MB   | ####2      |  43%
pandas-1.5.2         | 10.5 MB   | ####5      |  46%
pandas-1.5.2         | 10.5 MB   | ####8      |  48%
pandas-1.5.2         | 10.5 MB   | #####      |  51%
pandas-1.5.2         | 10.5 MB   | #####4     |  54%
pandas-1.5.2         | 10.5 MB   | #####7     |  57%
pandas-1.5.2         | 10.5 MB   | ######1    |  62%
pandas-1.5.2         | 10.5 MB   | ######4    |  65%
pandas-1.5.2         | 10.5 MB   | ######7    |  68%
pandas-1.5.2         | 10.5 MB   | #######    |  70%
pandas-1.5.2         | 10.5 MB   | #######3   |  73%
pandas-1.5.2         | 10.5 MB   | #######5   |  76%
pandas-1.5.2         | 10.5 MB   | #######8   |  79%
pandas-1.5.2         | 10.5 MB   | ########1  |  81%
pandas-1.5.2         | 10.5 MB   | ########4  |  84%
pandas-1.5.2         | 10.5 MB   | ########7  |  87%
pandas-1.5.2         | 10.5 MB   | #########  |  90%

==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 22.11.1

Please update conda by running

    $ conda update -n base -c defaults conda

pandas-1.5.2         | 10.5 MB   | #########2 |  93%
pandas-1.5.2         | 10.5 MB   | #########5 |  96%
pandas-1.5.2         | 10.5 MB   | #########8 |  99%
pandas-1.5.2         | 10.5 MB   | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Retrieving notices: ...working... done

In [4]:
%conda install matplotlib

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: c:\Users\ASUS\anaconda3\envs\env_gofood

  added / updated specs:
    - matplotlib


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    contourpy-1.0.5            |  py310h59b6b97_0         159 KB
    matplotlib-3.6.2           |  py310haa95532_0           9 KB
    matplotlib-base-3.6.2      |  py310h1094b8e_0         6.5 MB
    ------------------------------------------------------------
                                           Total:         6.7 MB

The following NEW packages will be INSTALLED:

  brotli             pkgs/main/win-64::brotli-1.0.9-h2bbff1b_7 None
  brotli-bin         pkgs/main/win-64::brotli-bin-1.0.9-h2bbff1b_7 None
  contourpy          pkgs/main/win-64::contourpy-1.0.5-py310h59b6b97_0 None
  cycler             pkgs/main/noarch::cycler-0.11.0-pyhd3eb1b0_0 None
  fonttools          pkgs/main/noarch::fonttools-4.25.0-pyhd3eb1b0_0 None
  freetype           pkgs/main/win-64::freetype-2.12.1-ha860e81_0 None
  kiwisolver         pkgs/main/win-64::kiwisolver-1.4.2-py310hd77b12b_0 None
  lerc               pkgs/main/win-64::lerc-3.0-hd77b12b_0 None
  libbrotlicommon    pkgs/main/win-64::libbrotlicommon-1.0.9-h2bbff1b_7 None
  libbrotlidec       pkgs/main/win-64::libbrotlidec-1.0.9-h2bbff1b_7 None
  libbrotlienc       pkgs/main/win-64::libbrotlienc-1.0.9-h2bbff1b_7 None
  libdeflate         pkgs/main/win-64::libdeflate-1.8-h2bbff1b_5 None
  libtiff            pkgs/main/win-64::libtiff-4.4.0-h8a3f274_2 None
  matplotlib         pkgs/main/win-64::matplotlib-3.6.2-py310haa95532_0 None
  matplotlib-base    pkgs/main/win-64::matplotlib-base-3.6.2-py310h1094b8e_0 None
  munkres            pkgs/main/noarch::munkres-1.1.4-py_0 None
  pillow             pkgs/main/win-64::pillow-9.2.0-py310hdc2b20a_1 None



Downloading and Extracting Packages

matplotlib-3.6.2     | 9 KB      |            |   0%
matplotlib-3.6.2     | 9 KB      | ########## | 100%
matplotlib-3.6.2     | 9 KB      | ########## | 100%

contourpy-1.0.5      | 159 KB    |            |   0%
contourpy-1.0.5      | 159 KB    | ##         |  20%
contourpy-1.0.5      | 159 KB    | ########## | 100%
contourpy-1.0.5      | 159 KB    | ########## | 100%

matplotlib-base-3.6. | 6.5 MB    |            |   0%
matplotlib-base-3.6. | 6.5 MB    | 1          |   2%
matplotlib-base-3.6. | 6.5 MB    | 6          |   6%
matplotlib-base-3.6. | 6.5 MB    | #          |  10%
matplotlib-base-3.6. | 6.5 MB    | #4         |  15%
matplotlib-base-3.6. | 6.5 MB    | ##         |  20%
matplotlib-base-3.6. | 6.5 MB    | ##5        |  25%
matplotlib-base-3.6. | 6.5 MB    | ###2       |  32%
matplotlib-base-3.6. | 6.5 MB    | ###8       |  39%
matplotlib-base-3.6. | 6.5 MB    | ####5      |  45%
matplotlib-base-3.6. | 6.5 MB    | #####      |  50%
matplotlib-base-3.6. | 6.5 MB    | #####6     |  57%
matplotlib-base-3.6. | 6.5 MB    | ######1    |  62%
matplotlib-base-3.6. | 6.5 MB    | ######8    |  69%
matplotlib-base-3.6. | 6.5 MB    | #######5   |  76%
matplotlib-base-3.6. | 6.5 MB    | ########1  |  82%
matplotlib-base-3.6. | 6.5 MB    | ########7  |  88%
matplotlib-base-3.6. | 6.5 MB    | #########4 |  94%
matplotlib-base-3.6. | 6.5 MB    | #########9 | 100%
matplotlib-base-3.6. | 6.5 MB    | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Retrieving notices: ...working... done

Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 22.11.1

Please update conda by running

    $ conda update -n base -c defaults conda

In [5]:
%conda install numpy

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

Retrieving notices: ...working... done

Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 22.11.1

Please update conda by running

    $ conda update -n base -c defaults conda

In [6]:
%conda install seaborn

Collecting package metadata (current_repodata.json): ...working... done
Note: you may need to restart the kernel to use updated packages.

Solving environment: ...working... done

## Package Plan ##

  environment location: c:\Users\ASUS\anaconda3\envs\env_gofood

  added / updated specs:
    - seaborn


The following NEW packages will be INSTALLED:

  seaborn            pkgs/main/win-64::seaborn-0.12.1-py310haa95532_0 None


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Retrieving notices: ...working... done

==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 22.11.1

Please update conda by running

    $ conda update -n base -c defaults conda

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
dataset = pd.read_csv('gofood_dataset.csv')
dataset

,merchant_name,merchant_area,category,display,product,price,discount_price,isDiscount,description
0,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Hot Almara Kopi (kopi Susu Gula Aren),20000.0,NaN,0,Sajian Kopi Susu Gula Aren Yang Berbeda Dari K...
1,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Ice Almara Kopi (kopi Susu Gula Aren),22000.0,NaN,0,Sajian Kopi Susu Gula Aren Yang Berbeda Dari K...
2,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Hot Millsis,20000.0,NaN,0,Sajian Susu Coklat Milo Dengan Racikan Khas 3 ...
3,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Ice Millsis,20000.0,NaN,0,Sajian Susu Coklat Milo Dengan Racikan Khas 3 ...
4,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Hot Millbro,22000.0,NaN,0,Sajian Susu Coklat Milo Plus Espresso Dengan R...
...,...,...,...,...,...,...,...,...,...
45190,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Hazelnut Choco Milktea,70000.0,NaN,0,1L Hazelnut Choco Milktea
45191,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Dolce Latte,80000.0,NaN,0,1L Dolce Latte
45192,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Chocoffe,80000.0,NaN,0,1L Chocoffe
45193,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Kopi Susu Gula Aren,85000.0,NaN,0,1L Kopi Susu Gula Aren
45194,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Salt Caramel Machiato,85000.0,NaN,0,1L Salt Caramel Machiato

In [14]:
dataset.head(11)

,merchant_name,merchant_area,category,display,product,price,discount_price,isDiscount,description
0,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Hot Almara Kopi (kopi Susu Gula Aren),20000.0,NaN,0,Sajian Kopi Susu Gula Aren Yang Berbeda Dari K...
1,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Ice Almara Kopi (kopi Susu Gula Aren),22000.0,NaN,0,Sajian Kopi Susu Gula Aren Yang Berbeda Dari K...
2,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Hot Millsis,20000.0,NaN,0,Sajian Susu Coklat Milo Dengan Racikan Khas 3 ...
3,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Ice Millsis,20000.0,NaN,0,Sajian Susu Coklat Milo Dengan Racikan Khas 3 ...
4,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Hot Millbro,22000.0,NaN,0,Sajian Susu Coklat Milo Plus Espresso Dengan R...
5,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Ice Millbro,22000.0,NaN,0,Sajian Susu Coklat Milo Plus Espresso Dengan R...
6,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Hot 330 Helateh,15000.0,NaN,0,Sajian Teh Tarik Segar Khas 3 : 30 Kopi
7,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Ice 330 Helateh,18000.0,NaN,0,Sajian Teh Tarik Segar Khas 3 : 30 Kopi
8,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Hot Ilusi Kopi,23000.0,NaN,0,Sajian Kopi Beraroma Rum Dengan Racikan Khas 3...
9,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Ice Ilusi Kopi,25000.0,NaN,0,Sajian Kopi Beraroma Rum Dengan Racikan Khas 3...
10,"330 Kopi, Ciledug",jakarta,Kopi/Minuman/Roti,Signature,Kopi Jelly,20000.0,NaN,0,NaN

In [15]:
dataset.tail(11)

,merchant_name,merchant_area,category,display,product,price,discount_price,isDiscount,description
45184,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,Coffee Series,Zegeroem Coffee,24300.0,NaN,0,Nikmatnya Espresso dipadu dengan susu segar da...
45185,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Chocolate,65000.0,NaN,0,1L Chocolate
45186,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Thai Tea,65000.0,NaN,0,1L Thai Tea
45187,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Lemon Tea,65000.0,NaN,0,1L Lemon Tea
45188,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Americano,65000.0,NaN,0,1L Americano
45189,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Black Oreo,70000.0,NaN,0,1L Black Oreo
45190,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Hazelnut Choco Milktea,70000.0,NaN,0,1L Hazelnut Choco Milktea
45191,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Dolce Latte,80000.0,NaN,0,1L Dolce Latte
45192,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Chocoffe,80000.0,NaN,0,1L Chocoffe
45193,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Kopi Susu Gula Aren,85000.0,NaN,0,1L Kopi Susu Gula Aren
45194,"Zeger!, Sidoarjo",surabaya,Minuman/Kopi,1L ZEGER BANGET !,1L Salt Caramel Machiato,85000.0,NaN,0,1L Salt Caramel Machiato

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45195 entries, 0 to 45194
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   merchant_name   45195 non-null  object
 1   merchant_area   45195 non-null  object
 2   category        45195 non-null  object
 3   display         45195 non-null  object
 4   product         45195 non-null  object
 5   price           45195 non-null  float64
 6   discount_price  2738 non-null   float64
 7   isDiscount      45195 non-null  int64
 8   description     21720 non-null  object
dtypes: float64(2), int64(1), object(6)
memory usage: 3.1+ MB

In [16]:
dataset.isna().sum()

merchant_name         0
merchant_area         0
category              0
display               0
product               0
price                 0
discount_price    42457
isDiscount            0
description       23475
dtype: int64